import { LayoutBasicAside, NavType, YunzaiNavTopic, YunzaiProjectInfo, YunzaiUser } from '@yelon/util/mtypes';
export declare const YZ_USER_KEY = "_yz_user";
export declare const YZ_PROJECT_INFO_KEY = "_yz_project_info";
export declare const YZ_CURRENT_KEY = "_yz_current";
export declare const YZ_HEADER_KEY = "_yz_header";
export declare const YZ_HEADER_TYPE_KEY = "_yz_header_type";
export declare const YZ_DEFAULT_ROUTE_KEY = "_yz_default_route";
export declare const YZ_TENANT_KEY = "_yz_tenant";
export declare const YZ_NEED_AUTH_KEY = "_yz_need_auth";
type returnSet<T> = (data: T) => void;
type returnGet<T> = () => T | null;
export declare function useLocalStorageUser(): [returnSet<YunzaiUser>, returnGet<YunzaiUser>];
export declare function useLocalStorageProjectInfo(): [returnSet<YunzaiProjectInfo>, returnGet<YunzaiProjectInfo>];
export declare function useLocalStorageCurrent(): [returnSet<LayoutBasicAside>, returnGet<LayoutBasicAside>];
export declare function useLocalStorageHeaderType(): [returnSet<NavType>, returnGet<NavType>];
export declare function useLocalStorageHeader(): [returnSet<YunzaiNavTopic[]>, returnGet<YunzaiNavTopic[]>];
export declare function useLocalStorageDefaultRoute(): [returnSet<string>, returnGet<string>];
export declare function useLocalStorageTenant(): [returnSet<string>, returnGet<string>];
export {};
