import { AfterViewInit, ComponentFactoryResolver, EventEmitter, Injector, OnDestroy } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import type { NzSafeAny } from 'ng-zorro-antd/core/types';
import { NzRangePickerComponent } from 'ng-zorro-antd/date-picker';
import { YunzaiConfigService, YunzaiDateRangePickerShortcut } from '@yelon/util/config';
import * as i0 from "@angular/core";
export declare class RangePickerDirective implements OnDestroy, AfterViewInit {
    private dom;
    private nativeComp;
    private resolver;
    private injector;
    static ngAcceptInputType_shortcut: YunzaiDateRangePickerShortcut | string | null;
    private defaultShortcuts;
    private _shortcut;
    private destroy$;
    private shortcutFactory;
    start: Date | null;
    end: Date | null;
    set shortcut(val: YunzaiDateRangePickerShortcut | null);
    get shortcut(): YunzaiDateRangePickerShortcut | null;
    ngModelEnd: NzSafeAny;
    readonly ngModelEndChange: EventEmitter<any>;
    private get dp();
    private get srv();
    constructor(dom: DomSanitizer, configSrv: YunzaiConfigService, nativeComp: NzRangePickerComponent, resolver: ComponentFactoryResolver, injector: Injector);
    private cd;
    private overrideNative;
    private refreshShortcut;
    ngAfterViewInit(): void;
    private destoryShortcut;
    ngOnDestroy(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<RangePickerDirective, [null, null, { optional: true; host: true; }, null, null]>;
    static ɵdir: i0.ɵɵDirectiveDeclaration<RangePickerDirective, "nz-range-picker[extend]", ["extendRangePicker"], { "shortcut": "shortcut"; "ngModelEnd": "ngModelEnd"; }, { "ngModelEndChange": "ngModelEndChange"; }, never>;
}
