import { ChangeDetectorRef, Injector, OnDestroy, OnInit } from '@angular/core';
import { Observable, Subscription } from 'rxjs';
import { NoticeIconSelect, NoticeItem } from '@yelon/abc/notice-icon';
import { _HttpClient } from '@yelon/theme';
import { NzI18nService } from 'ng-zorro-antd/i18n';
import { NzMessageService } from 'ng-zorro-antd/message';
import { YunzaiI18NService } from '../yunzai-i18n.service';
import * as i0 from "@angular/core";
export declare class YunzaiNotifyComponent implements OnInit, OnDestroy {
    private injector;
    private msg;
    private y18n;
    private nzI18n;
    private cdr;
    private httpClient;
    data: NoticeItem[];
    loading: boolean;
    count: number;
    subs: Subscription[];
    constructor(injector: Injector, msg: NzMessageService, y18n: YunzaiI18NService, nzI18n: NzI18nService, cdr: ChangeDetectorRef, httpClient: _HttpClient);
    ngOnInit(): void;
    loadData(): void;
    loadMessage(): Observable<void>;
    loadTodo(): Observable<void>;
    clear(type: string): void;
    select(res: NoticeIconSelect): void;
    ngOnDestroy(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<YunzaiNotifyComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<YunzaiNotifyComponent, "yunzai-notify", never, {}, {}, never, never, false, never>;
}
