import * as i0 from "@angular/core";
import * as i1 from "./widgets/yunzai-clear-storage.component";
import * as i2 from "./widgets/yunzai-fullscreen.component";
import * as i3 from "./widgets/yunzai-i18n.component";
import * as i4 from "./widgets/yunzai-notify.component";
import * as i5 from "./widgets/yunzai-theme-btn.component";
import * as i6 from "./widgets/yunzai-user.component";
import * as i7 from "./layout-basic/layout-basic.component";
import * as i8 from "./layout-nav/layout-nav-application.component";
import * as i9 from "./layout-nav/layout-nav-group.component";
import * as i10 from "./layout-nav/layout-nav-tile.component";
import * as i11 from "@angular/router";
import * as i12 from "@yelon/abc/reuse-tab";
import * as i13 from "@yelon/theme/layout-default";
import * as i14 from "@angular/common";
import * as i15 from "ng-zorro-antd/tabs";
import * as i16 from "ng-zorro-antd/tooltip";
import * as i17 from "ng-zorro-antd/dropdown";
import * as i18 from "ng-zorro-antd/avatar";
import * as i19 from "@yelon/abc/notice-icon";
import * as i20 from "@angular/forms";
import * as i21 from "ng-zorro-antd/grid";
import * as i22 from "@yelon/theme";
import * as i23 from "ng-zorro-antd/input";
import * as i24 from "ng-zorro-antd/icon";
export declare class YunzaiLayoutModule {
    static ɵfac: i0.ɵɵFactoryDeclaration<YunzaiLayoutModule, never>;
    static ɵmod: i0.ɵɵNgModuleDeclaration<YunzaiLayoutModule, [typeof i1.YunzaiClearStorageComponent, typeof i2.YunzaiFullScreenComponent, typeof i3.YunzaiI18NComponent, typeof i4.YunzaiNotifyComponent, typeof i5.YunzaiThemeBtnComponent, typeof i6.YunzaiUserComponent, typeof i7.YunzaiLayoutBasicComponent, typeof i8.LayoutNavApplicationComponent, typeof i9.LayoutNavGroupComponent, typeof i10.LayoutNavTileComponent], [typeof i11.RouterModule, typeof i12.ReuseTabModule, typeof i13.LayoutDefaultModule, typeof i14.CommonModule, typeof i15.NzTabsModule, typeof i14.NgOptimizedImage, typeof i16.NzToolTipModule, typeof i17.NzDropDownModule, typeof i18.NzAvatarModule, typeof i19.NoticeIconModule, typeof i20.FormsModule, typeof i21.NzGridModule, typeof i22.YunzaiThemeModule, typeof i23.NzInputModule, typeof i24.NzIconModule], [typeof i1.YunzaiClearStorageComponent, typeof i2.YunzaiFullScreenComponent, typeof i3.YunzaiI18NComponent, typeof i4.YunzaiNotifyComponent, typeof i5.YunzaiThemeBtnComponent, typeof i6.YunzaiUserComponent, typeof i7.YunzaiLayoutBasicComponent, typeof i8.LayoutNavApplicationComponent, typeof i9.LayoutNavGroupComponent, typeof i10.LayoutNavTileComponent]>;
    static ɵinj: i0.ɵɵInjectorDeclaration<YunzaiLayoutModule>;
}
