import { TemplateRef } from '@angular/core';
import { Observable } from 'rxjs';
import type { REP_TYPE } from '@yelon/theme';
import { YunzaiConfigService } from '@yelon/util/config';
import { BooleanInput, NumberInput } from '@yelon/util/decorator';
import { SEErrorRefresh, SELayout } from './se.types';
export declare class SEContainerComponent {
    static ngAcceptInputType_col: NumberInput;
    static ngAcceptInputType_colInCon: NumberInput;
    static ngAcceptInputType_labelWidth: NumberInput;
    static ngAcceptInputType_firstVisual: BooleanInput;
    static ngAcceptInputType_ignoreDirty: BooleanInput;
    static ngAcceptInputType_line: BooleanInput;
    static ngAcceptInputType_noColon: BooleanInput;
    private errorNotify$;
    colInCon: REP_TYPE;
    col: REP_TYPE;
    labelWidth: number;
    noColon: boolean;
    title?: string | TemplateRef<void> | null;
    get gutter(): number | string;
    set gutter(value: number | string);
    private _gutter;
    get nzLayout(): SELayout;
    set nzLayout(value: SELayout);
    private _nzLayout;
    size: 'default' | 'compact';
    firstVisual: boolean;
    ignoreDirty: boolean;
    line: boolean;
    set errors(val: SEErrorRefresh[]);
    get margin(): number;
    get errorNotify(): Observable<SEErrorRefresh>;
    constructor(configSrv: YunzaiConfigService);
    setErrors(errors: SEErrorRefresh[]): void;
}
