import { AutoFocusModule } from '@yelon/abc/auto-focus';
import { AvatarListModule } from '@yelon/abc/avatar-list';
import { CountDownModule } from '@yelon/abc/count-down';
import { DatePickerModule } from '@yelon/abc/date-picker';
import { DownFileModule } from '@yelon/abc/down-file';
import { EllipsisModule } from '@yelon/abc/ellipsis';
import { ErrorCollectModule } from '@yelon/abc/error-collect';
import { ExceptionModule } from '@yelon/abc/exception';
import { FooterToolbarModule } from '@yelon/abc/footer-toolbar';
import { GlobalFooterModule } from '@yelon/abc/global-footer';
import { ImageModule } from '@yelon/abc/image';
import { LetModule } from '@yelon/abc/let';
import { LoadingModule } from '@yelon/abc/loading';
import { MediaModule } from '@yelon/abc/media';
import { NoticeIconModule } from '@yelon/abc/notice-icon';
import { OnboardingModule } from '@yelon/abc/onboarding';
import { PageHeaderModule } from '@yelon/abc/page-header';
import { PdfModule } from '@yelon/abc/pdf';
import { QRModule } from '@yelon/abc/qr';
import { QuickMenuModule } from '@yelon/abc/quick-menu';
import { ResultModule } from '@yelon/abc/result';
import { ReuseTabModule } from '@yelon/abc/reuse-tab';
import { SEModule } from '@yelon/abc/se';
import { SGModule } from '@yelon/abc/sg';
import { SVModule } from '@yelon/abc/sv';
import { TagSelectModule } from '@yelon/abc/tag-select';
import { YelonACLModule } from '@yelon/acl';
import { G2BarModule } from '@yelon/chart/bar';
import { G2CardModule } from '@yelon/chart/card';
import { ChartEChartsModule } from '@yelon/chart/chart-echarts';
import { G2CustomModule } from '@yelon/chart/custom';
import { G2GaugeModule } from '@yelon/chart/gauge';
import { G2MiniAreaModule } from '@yelon/chart/mini-area';
import { G2MiniBarModule } from '@yelon/chart/mini-bar';
import { G2MiniProgressModule } from '@yelon/chart/mini-progress';
import { NumberInfoModule } from '@yelon/chart/number-info';
import { G2PieModule } from '@yelon/chart/pie';
import { G2RadarModule } from '@yelon/chart/radar';
import { G2SingleBarModule } from '@yelon/chart/single-bar';
import { G2TagCloudModule } from '@yelon/chart/tag-cloud';
import { G2TimelineModule } from '@yelon/chart/timeline';
import { TrendModule } from '@yelon/chart/trend';
import { G2WaterWaveModule } from '@yelon/chart/water-wave';
import { YelonFormModule } from '@yelon/form';
import { YunzaiThemeModule } from '@yelon/theme';
import { LayoutDefaultModule } from '@yelon/theme/layout-default';
import { SettingDrawerModule } from '@yelon/theme/setting-drawer';
import { ThemeBtnModule } from '@yelon/theme/theme-btn';
import { CurrencyPipeModule, FormatPipeModule, FilterPipeModule } from '@yelon/util';
import { NzAffixModule } from 'ng-zorro-antd/affix';
import { NzAlertModule } from 'ng-zorro-antd/alert';
import { NzAnchorModule } from 'ng-zorro-antd/anchor';
import { NzAvatarModule } from 'ng-zorro-antd/avatar';
import { NzBackTopModule } from 'ng-zorro-antd/back-top';
import { NzBadgeModule } from 'ng-zorro-antd/badge';
import { NzBreadCrumbModule } from 'ng-zorro-antd/breadcrumb';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzCardModule } from 'ng-zorro-antd/card';
import { NzCarouselModule } from 'ng-zorro-antd/carousel';
import { NzCheckboxModule } from 'ng-zorro-antd/checkbox';
import { NzHighlightModule } from 'ng-zorro-antd/core/highlight';
import { NzDatePickerModule } from 'ng-zorro-antd/date-picker';
import { NzDividerModule } from 'ng-zorro-antd/divider';
import { NzDrawerModule } from 'ng-zorro-antd/drawer';
import { NzDropDownModule } from 'ng-zorro-antd/dropdown';
import { NzEmptyModule } from 'ng-zorro-antd/empty';
import { NzFormModule } from 'ng-zorro-antd/form';
import { NzGridModule } from 'ng-zorro-antd/grid';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { NzInputModule } from 'ng-zorro-antd/input';
import { NzInputNumberModule } from 'ng-zorro-antd/input-number';
import { NzListModule } from 'ng-zorro-antd/list';
import { NzMessageModule } from 'ng-zorro-antd/message';
import { NzModalModule } from 'ng-zorro-antd/modal';
import { NzPaginationModule } from 'ng-zorro-antd/pagination';
import { NzPopoverModule } from 'ng-zorro-antd/popover';
import { NzRadioModule } from 'ng-zorro-antd/radio';
import { NzResizableModule } from 'ng-zorro-antd/resizable';
import { NzSelectModule } from 'ng-zorro-antd/select';
import { NzSpinModule } from 'ng-zorro-antd/spin';
import { NzStepsModule } from 'ng-zorro-antd/steps';
import { NzSwitchModule } from 'ng-zorro-antd/switch';
import { NzTableModule } from 'ng-zorro-antd/table';
import { NzTabsModule } from 'ng-zorro-antd/tabs';
import { NzTagModule } from 'ng-zorro-antd/tag';
import { NzToolTipModule } from 'ng-zorro-antd/tooltip';
import { NzTreeModule } from 'ng-zorro-antd/tree';
import { NzUploadModule } from 'ng-zorro-antd/upload';
import { NgModule } from '@angular/core';
import { AccountBookTwoTone, AccountBookFill, AccountBookOutline, AlertTwoTone, AlertFill, AlibabaOutline, AimOutline, AlipayCircleFill, AlertOutline, AlignCenterOutline, AlipayCircleOutline, AlipayOutline, AlignLeftOutline, AlignRightOutline, AmazonOutline, AliwangwangOutline, AliyunOutline, AlipaySquareFill, AmazonCircleFill, AndroidFill, AliwangwangFill, AntCloudOutline, AmazonSquareFill, AndroidOutline, ApartmentOutline, ApiTwoTone, ApiFill, ApiOutline, AntDesignOutline, AppstoreAddOutline, AppstoreFill, AppleOutline, AppstoreOutline, ArrowDownOutline, AppleFill, ArrowsAltOutline, AppstoreTwoTone, ArrowUpOutline, AreaChartOutline, ArrowLeftOutline, AudioFill, ArrowRightOutline, AudioTwoTone, AuditOutline, AudioMutedOutline, BackwardFill, AudioOutline, BackwardOutline, BankFill, BarcodeOutline, BellFill, BankTwoTone, BarsOutline, BankOutline, BehanceCircleFill, BehanceSquareFill, BoldOutline, BellOutline, BehanceOutline, BlockOutline, BehanceSquareOutline, BgColorsOutline, BellTwoTone, BarChartOutline, BookTwoTone, BookFill, BorderOuterOutline, BorderLeftOutline, BorderBottomOutline, BorderHorizontalOutline, BorderTopOutline, BorderOutline, BorderInnerOutline, BorderRightOutline, BoxPlotOutline, BoxPlotFill, BoxPlotTwoTone, BookOutline, BorderlessTableOutline, BorderVerticleOutline, BuildTwoTone, BuildOutline, BugFill, BugOutline, BugTwoTone, BulbFill, BulbTwoTone, BuildFill, BulbOutline, CalculatorFill, CalculatorTwoTone, CalendarFill, CalendarOutline, CalculatorOutline, CalendarTwoTone, CameraOutline, CameraFill, CameraTwoTone, CarTwoTone, CaretDownOutline, CarOutline, CaretLeftFill, CarFill, CaretRightOutline, CaretDownFill, CaretUpOutline, CaretRightFill, CarryOutFill, CarryOutOutline, CaretLeftOutline, CaretUpFill, BranchesOutline, CarryOutTwoTone, CheckCircleFill, CheckCircleOutline, CheckSquareOutline, CheckCircleTwoTone, CiCircleTwoTone, CheckOutline, CheckSquareTwoTone, CiOutline, CheckSquareFill, CiTwoTone, ChromeOutline, ClockCircleOutline, CiCircleOutline, ChromeFill, ClearOutline, CloseCircleTwoTone, CiCircleFill, CloseCircleOutline, ClockCircleFill, CloseCircleFill, ClockCircleTwoTone, CloseOutline, CloseSquareOutline, CloseSquareFill, CloudFill, CloseSquareTwoTone, CloudDownloadOutline, CloudTwoTone, CloudServerOutline, CloudUploadOutline, CloudSyncOutline, ClusterOutline, CodeSandboxCircleFill, CodeFill, CodepenCircleOutline, CloudOutline, CodeSandboxOutline, CodeOutline, CodeSandboxSquareFill, CodeTwoTone, CodepenSquareFill, CodepenOutline, CoffeeOutline, ColumnWidthOutline, CompressOutline, ColumnHeightOutline, CodepenCircleFill, CompassTwoTone, CommentOutline, ContainerFill, CompassOutline, ConsoleSqlOutline, ContactsOutline, ContainerTwoTone, ContactsFill, ContactsTwoTone, ContainerOutline, ControlFill, CopyFill, CopyOutline, CompassFill, CopyTwoTone, CopyrightOutline, CopyrightCircleOutline, ControlTwoTone, ControlOutline, CreditCardFill, CopyrightTwoTone, CrownFill, CopyrightCircleFill, CrownOutline, CustomerServiceTwoTone, CreditCardOutline, CustomerServiceOutline, DashboardTwoTone, CrownTwoTone, CreditCardTwoTone, CustomerServiceFill, DashboardFill, DashOutline, DatabaseOutline, DatabaseTwoTone, DatabaseFill, DashboardOutline, DeleteTwoTone, DeleteRowOutline, DeleteColumnOutline, DeliveredProcedureOutline, DeleteOutline, CopyrightCircleTwoTone, DesktopOutline, DeleteFill, DiffOutline, DiffFill, DeploymentUnitOutline, DiffTwoTone, DingtalkOutline, DollarCircleFill, DislikeFill, DingtalkSquareFill, DisconnectOutline, DollarCircleTwoTone, DollarOutline, DingtalkCircleFill, DislikeTwoTone, DollarTwoTone, DownCircleFill, DislikeOutline, DollarCircleOutline, DoubleLeftOutline, DownSquareFill, DownOutline, DownSquareOutline, DownSquareTwoTone, DownCircleTwoTone, DoubleRightOutline, DownCircleOutline, DownloadOutline, DotChartOutline, DribbbleCircleFill, DribbbleOutline, DribbbleSquareOutline, DropboxCircleFill, DingdingOutline, EditOutline, DribbbleSquareFill, DropboxSquareFill, EllipsisOutline, EnvironmentFill, EditFill, EnterOutline, EuroCircleFill, EuroTwoTone, EuroCircleOutline, EditTwoTone, EuroOutline, EnvironmentTwoTone, ExclamationCircleFill, ExpandAltOutline, EuroCircleTwoTone, ExclamationCircleTwoTone, EnvironmentOutline, ExperimentOutline, ExperimentFill, ExpandOutline, ExceptionOutline, ExportOutline, ExperimentTwoTone, ExclamationCircleOutline, ExclamationOutline, EyeFill, EyeInvisibleFill, EyeInvisibleTwoTone, DropboxOutline, DragOutline, FacebookOutline, FacebookFill, EyeTwoTone, EyeOutline, FastForwardFill, FieldBinaryOutline, FieldNumberOutline, FastBackwardOutline, FileAddFill, FastBackwardFill, FileExcelFill, FastForwardOutline, FieldStringOutline, FileDoneOutline, FileAddTwoTone, FileExcelTwoTone, FileExclamationFill, FileAddOutline, FileExclamationOutline, FieldTimeOutline, FileImageTwoTone, FileExcelOutline, FileExclamationTwoTone, FileImageFill, FileGifOutline, FileFill, FileMarkdownTwoTone, FileMarkdownOutline, FallOutline, FileImageOutline, EyeInvisibleOutline, FilePdfOutline, FileSearchOutline, FilePptTwoTone, FilePdfTwoTone, FileJpgOutline, FileTextFill, FilePptOutline, FileSyncOutline, FilePptFill, FileUnknownOutline, FileProtectOutline, FileTextTwoTone, FileWordFill, FileUnknownTwoTone, FileWordTwoTone, FileUnknownFill, FileTextOutline, FileZipFill, FilterTwoTone, FilterFill, FileWordOutline, FireOutline, FireTwoTone, FileZipOutline, FilterOutline, FlagTwoTone, FileTwoTone, FilePdfFill, FileOutline, FileMarkdownFill, FileZipTwoTone, FlagOutline, FolderAddTwoTone, FolderOpenFill, FireFill, FlagFill, FolderOutline, FolderViewOutline, FolderTwoTone, FontColorsOutline, FolderOpenTwoTone, FolderFill, ForwardOutline, FolderOpenOutline, ForkOutline, ForwardFill, FormatPainterOutline, FormatPainterFill, FormOutline, FrownFill, FrownTwoTone, FullscreenOutline, FontSizeOutline, FundFill, FunctionOutline, FundViewOutline, FullscreenExitOutline, GifOutline, FundProjectionScreenOutline, FundTwoTone, FolderAddFill, FunnelPlotTwoTone, GiftOutline, FunnelPlotFill, FundOutline, FrownOutline, GithubOutline, GoldFill, FolderAddOutline, GitlabFill, GiftFill, GitlabOutline, GoldTwoTone, GoogleCircleFill, GiftTwoTone, GooglePlusCircleFill, GoldOutline, GithubFill, GoogleOutline, GooglePlusOutline, GoogleSquareFill, GoldenFill, HddTwoTone, GooglePlusSquareFill, GlobalOutline, HeartOutline, HeartTwoTone, GroupOutline, HeartFill, HeatMapOutline, GatewayOutline, FunnelPlotOutline, HddFill, HomeFill, HighlightFill, HomeOutline, HistoryOutline, HighlightOutline, HddOutline, HourglassFill, HomeTwoTone, HourglassTwoTone, Html5Outline, Html5Fill, IdcardFill, Html5TwoTone, HourglassOutline, IdcardTwoTone, IdcardOutline, IeOutline, IeCircleFill, IeSquareFill, InboxOutline, ImportOutline, InfoCircleOutline, InfoCircleTwoTone, InsertRowAboveOutline, InsertRowRightOutline, InfoCircleFill, InfoOutline, InsertRowBelowOutline, HighlightTwoTone, InsuranceFill, InstagramFill, InteractionFill, InsertRowLeftOutline, InstagramOutline, InteractionOutline, ItalicOutline, InteractionTwoTone, LayoutOutline, IssuesCloseOutline, LayoutFill, LaptopOutline, LeftCircleFill, LayoutTwoTone, KeyOutline, LeftOutline, LeftCircleOutline, LeftSquareOutline, LeftSquareFill, LeftCircleTwoTone, LikeFill, LeftSquareTwoTone, LineOutline, LikeTwoTone, LinkedinOutline, LineChartOutline, LineHeightOutline, LinkedinFill, LinkOutline, LikeOutline, InsuranceOutline, Loading3QuartersOutline, LockFill, InsuranceTwoTone, MacCommandOutline, LockTwoTone, LoadingOutline, MailOutline, LoginOutline, MedicineBoxOutline, MailFill, MailTwoTone, MacCommandFill, ManOutline, MedicineBoxFill, MedicineBoxTwoTone, MediumCircleFill, MediumOutline, MehFill, MediumWorkmarkOutline, MenuFoldOutline, MehOutline, MediumSquareFill, MessageTwoTone, MehTwoTone, MergeCellsOutline, MinusCircleFill, MenuOutline, MenuUnfoldOutline, MessageFill, MinusCircleTwoTone, LockOutline, MinusOutline, MinusCircleOutline, LogoutOutline, MessageOutline, MoneyCollectFill, MinusSquareOutline, MinusSquareTwoTone, MobileOutline, MobileTwoTone, MoneyCollectOutline, MoreOutline, NotificationFill, NotificationOutline, MoneyCollectTwoTone, NodeIndexOutline, NodeExpandOutline, MonitorOutline, OrderedListOutline, NodeCollapseOutline, NumberOutline, PaperClipOutline, NotificationTwoTone, PauseCircleFill, PartitionOutline, PauseOutline, OneToOneOutline, PayCircleOutline, PayCircleFill, MinusSquareFill, PauseCircleOutline, PauseCircleTwoTone, PicCenterOutline, PicRightOutline, PercentageOutline, MobileFill, PictureOutline, PictureFill, PhoneTwoTone, PhoneFill, PieChartFill, PictureTwoTone, PieChartOutline, PlaySquareFill, PlayCircleTwoTone, PlayCircleFill, PlusCircleFill, PlaySquareTwoTone, PlaySquareOutline, PlayCircleOutline, PieChartTwoTone, PlusCircleOutline, PlusSquareFill, PoundCircleFill, PlusSquareOutline, PlusOutline, PoundOutline, PoundCircleOutline, PlusSquareTwoTone, PlusCircleTwoTone, PoweroffOutline, PoundCircleTwoTone, PhoneOutline, PrinterFill, PicLeftOutline, ProjectTwoTone, PrinterOutline, ProjectFill, ProfileOutline, ProfileTwoTone, ProjectOutline, PropertySafetyFill, PullRequestOutline, PropertySafetyOutline, PushpinOutline, PushpinTwoTone, PropertySafetyTwoTone, PushpinFill, QqOutline, QqCircleFill, QrcodeOutline, QqSquareFill, QuestionCircleTwoTone, QuestionCircleFill, RadarChartOutline, RadiusUprightOutline, QuestionCircleOutline, QuestionOutline, ReadFill, RadiusUpleftOutline, RadiusBottomleftOutline, RadiusSettingOutline, RadiusBottomrightOutline, ProfileFill, PrinterTwoTone, ReadOutline, ReconciliationFill, ReloadOutline, ReconciliationOutline, RedEnvelopeTwoTone, RedditCircleFill, RedoOutline, RedEnvelopeFill, RedditOutline, RestTwoTone, RightCircleOutline, RestOutline, RedditSquareFill, RestFill, RightCircleTwoTone, RightOutline, RightSquareFill, RightCircleFill, RightSquareOutline, RetweetOutline, RiseOutline, RightSquareTwoTone, RobotFill, RocketOutline, RobotOutline, RocketTwoTone, RocketFill, RedEnvelopeOutline, RollbackOutline, RotateRightOutline, RotateLeftOutline, ReconciliationTwoTone, SafetyCertificateTwoTone, SaveOutline, SafetyOutline, SaveFill, SaveTwoTone, ScheduleFill, SafetyCertificateOutline, ScanOutline, ScheduleTwoTone, SearchOutline, ScheduleOutline, SecurityScanTwoTone, SecurityScanOutline, ScissorOutline, SelectOutline, SecurityScanFill, SendOutline, SettingOutline, SettingTwoTone, SettingFill, ShareAltOutline, ShopOutline, ShopFill, ShopTwoTone, ShrinkOutline, ShakeOutline, ShoppingOutline, ShoppingCartOutline, ShoppingFill, SisternodeOutline, ShoppingTwoTone, SafetyCertificateFill, SkinOutline, SignalFill, SketchOutline, SkinTwoTone, SketchSquareFill, SkypeFill, SkinFill, SlackCircleFill, SlackSquareFill, SlidersTwoTone, SkypeOutline, SlidersFill, SlackSquareOutline, SmallDashOutline, SmileTwoTone, SlidersOutline, SnippetsFill, SnippetsOutline, SmileOutline, SolutionOutline, SlackOutline, SnippetsTwoTone, SoundTwoTone, SortAscendingOutline, SoundFill, SortDescendingOutline, SmileFill, SoundOutline, SplitCellsOutline, SketchCircleFill, StarOutline, StockOutline, StarTwoTone, StepForwardFill, StarFill, StepBackwardFill, StepForwardOutline, StopFill, SubnodeOutline, SwapLeftOutline, StopOutline, StopTwoTone, SwapRightOutline, SwapOutline, SwitcherTwoTone, SwitcherOutline, SyncOutline, StrikethroughOutline, SwitcherFill, TagOutline, TabletTwoTone, TabletOutline, TabletFill, TableOutline, TagsFill, TagFill, TagsTwoTone, TaobaoCircleOutline, StepBackwardOutline, TagsOutline, TagTwoTone, TaobaoOutline, ThunderboltOutline, TaobaoSquareFill, TeamOutline, TaobaoCircleFill, ThunderboltTwoTone, ToolFill, ThunderboltFill, ToTopOutline, ToolOutline, ToolTwoTone, TrademarkCircleFill, TrophyFill, TrademarkCircleTwoTone, TransactionOutline, TrademarkCircleOutline, TranslationOutline, TwitterCircleFill, TrophyOutline, TrademarkOutline, TrophyTwoTone, TwitterSquareFill, UnlockFill, TwitterOutline, UnderlineOutline, UndoOutline, UpCircleFill, UngroupOutline, UnlockTwoTone, UnlockOutline, UpOutline, UsbFill, UpCircleOutline, UnorderedListOutline, UpCircleTwoTone, UpSquareFill, UpSquareOutline, UserAddOutline, UsbTwoTone, UsergroupDeleteOutline, UpSquareTwoTone, UserOutline, UsbOutline, UserDeleteOutline, UserSwitchOutline, VerticalLeftOutline, VerticalAlignBottomOutline, VerifiedOutline, UsergroupAddOutline, UploadOutline, VerticalAlignMiddleOutline, VerticalAlignTopOutline, VerticalRightOutline, VideoCameraOutline, VideoCameraAddOutline, VideoCameraTwoTone, VideoCameraFill, WalletOutline, WalletFill, WarningFill, WarningOutline, WechatOutline, WalletTwoTone, WeiboCircleFill, WarningTwoTone, WeiboSquareFill, WeiboOutline, WeiboSquareOutline, WeiboCircleOutline, WechatFill, WhatsAppOutline, WifiOutline, WomanOutline, YoutubeFill, YahooOutline, WindowsFill, WindowsOutline, YoutubeOutline, YuqueOutline, ZhihuCircleFill, YuqueFill, ZhihuOutline, ZhihuSquareFill, ZoomInOutline, ZoomOutOutline, YahooFill } from '@ant-design/icons-angular/icons';

const YZ_SHARED_YELON_MODULES = [
    YunzaiThemeModule,
    NoticeIconModule,
    ReuseTabModule,
    LayoutDefaultModule,
    YelonACLModule,
    YelonFormModule,
    AvatarListModule,
    CountDownModule,
    DatePickerModule,
    DownFileModule,
    EllipsisModule,
    // STModule,
    SVModule,
    SEModule,
    SGModule,
    ImageModule,
    LoadingModule,
    QRModule,
    OnboardingModule,
    ErrorCollectModule,
    ExceptionModule,
    FooterToolbarModule,
    GlobalFooterModule,
    GlobalFooterModule,
    PageHeaderModule,
    ResultModule,
    TagSelectModule,
    NoticeIconModule,
    QuickMenuModule,
    G2BarModule,
    G2CardModule,
    G2CustomModule,
    G2GaugeModule,
    G2MiniAreaModule,
    G2MiniBarModule,
    G2MiniProgressModule,
    G2PieModule,
    G2RadarModule,
    G2SingleBarModule,
    G2TagCloudModule,
    G2TimelineModule,
    G2WaterWaveModule,
    ChartEChartsModule,
    NumberInfoModule,
    TrendModule,
    ReuseTabModule,
    MediaModule,
    ThemeBtnModule,
    SettingDrawerModule,
    PdfModule,
    CurrencyPipeModule,
    FormatPipeModule,
    FilterPipeModule,
    AutoFocusModule,
    LetModule
];

const YZ_SHARED_ZORRO_MODULES = [
    NzTreeModule,
    NzButtonModule,
    NzMessageModule,
    NzBackTopModule,
    NzDropDownModule,
    NzGridModule,
    NzCarouselModule,
    NzCheckboxModule,
    NzToolTipModule,
    NzPopoverModule,
    NzSelectModule,
    NzIconModule,
    NzAffixModule,
    NzBadgeModule,
    NzAlertModule,
    NzModalModule,
    NzTableModule,
    NzDrawerModule,
    NzTabsModule,
    NzInputModule,
    NzDatePickerModule,
    NzTagModule,
    NzInputNumberModule,
    NzBreadCrumbModule,
    NzStepsModule,
    NzListModule,
    NzSwitchModule,
    NzRadioModule,
    NzFormModule,
    NzAvatarModule,
    NzCardModule,
    NzSpinModule,
    NzDividerModule,
    NzResizableModule,
    NzAnchorModule,
    NzUploadModule,
    NzPaginationModule,
    NzEmptyModule,
    NzHighlightModule
];

const THIRDMODULES = [];
const COMPONENTS = [];
const DIRECTIVES = [];
class YzSharedModule {
}
YzSharedModule.decorators = [
    { type: NgModule, args: [{
                imports: [...YZ_SHARED_YELON_MODULES, ...YZ_SHARED_ZORRO_MODULES, ...THIRDMODULES],
                declarations: [...COMPONENTS, ...DIRECTIVES],
                exports: [...YZ_SHARED_YELON_MODULES, ...YZ_SHARED_ZORRO_MODULES, ...THIRDMODULES, ...COMPONENTS, ...DIRECTIVES]
            },] }
];

/*
 * Automatically generated by 'ng g ng-yunzai:plugin icon'
 * @see https://ng.yunzainfo.com/cli/plugin#icon
 */
const ICONS = [
    AccountBookTwoTone,
    AccountBookFill,
    AccountBookOutline,
    AlertTwoTone,
    AlertFill,
    AlibabaOutline,
    AimOutline,
    AlipayCircleFill,
    AlertOutline,
    AlignCenterOutline,
    AlipayCircleOutline,
    AlipayOutline,
    AlignLeftOutline,
    AlignRightOutline,
    AmazonOutline,
    AliwangwangOutline,
    AliyunOutline,
    AlipaySquareFill,
    AmazonCircleFill,
    AndroidFill,
    AliwangwangFill,
    AntCloudOutline,
    AmazonSquareFill,
    AndroidOutline,
    ApartmentOutline,
    ApiTwoTone,
    ApiFill,
    ApiOutline,
    AntDesignOutline,
    AppstoreAddOutline,
    AppstoreFill,
    AppleOutline,
    AppstoreOutline,
    ArrowDownOutline,
    AppleFill,
    ArrowsAltOutline,
    AppstoreTwoTone,
    ArrowUpOutline,
    AreaChartOutline,
    ArrowLeftOutline,
    AudioFill,
    ArrowRightOutline,
    AudioTwoTone,
    AuditOutline,
    AudioMutedOutline,
    BackwardFill,
    AudioOutline,
    BackwardOutline,
    BankFill,
    BarcodeOutline,
    BellFill,
    BankTwoTone,
    BarsOutline,
    BankOutline,
    BehanceCircleFill,
    BehanceSquareFill,
    BoldOutline,
    BellOutline,
    BehanceOutline,
    BlockOutline,
    BehanceSquareOutline,
    BgColorsOutline,
    BellTwoTone,
    BarChartOutline,
    BookTwoTone,
    BookFill,
    BorderOuterOutline,
    BorderLeftOutline,
    BorderBottomOutline,
    BorderHorizontalOutline,
    BorderTopOutline,
    BorderOutline,
    BorderInnerOutline,
    BorderRightOutline,
    BoxPlotOutline,
    BoxPlotFill,
    BoxPlotTwoTone,
    BookOutline,
    BorderlessTableOutline,
    BorderVerticleOutline,
    BuildTwoTone,
    BuildOutline,
    BugFill,
    BugOutline,
    BugTwoTone,
    BulbFill,
    BulbTwoTone,
    BuildFill,
    BulbOutline,
    CalculatorFill,
    CalculatorTwoTone,
    CalendarFill,
    CalendarOutline,
    CalculatorOutline,
    CalendarTwoTone,
    CameraOutline,
    CameraFill,
    CameraTwoTone,
    CarTwoTone,
    CaretDownOutline,
    CarOutline,
    CaretLeftFill,
    CarFill,
    CaretRightOutline,
    CaretDownFill,
    CaretUpOutline,
    CaretRightFill,
    CarryOutFill,
    CarryOutOutline,
    CaretLeftOutline,
    CaretUpFill,
    BranchesOutline,
    CarryOutTwoTone,
    CheckCircleFill,
    CheckCircleOutline,
    CheckSquareOutline,
    CheckCircleTwoTone,
    CiCircleTwoTone,
    CheckOutline,
    CheckSquareTwoTone,
    CiOutline,
    CheckSquareFill,
    CiTwoTone,
    ChromeOutline,
    ClockCircleOutline,
    CiCircleOutline,
    ChromeFill,
    ClearOutline,
    CloseCircleTwoTone,
    CiCircleFill,
    CloseCircleOutline,
    ClockCircleFill,
    CloseCircleFill,
    ClockCircleTwoTone,
    CloseOutline,
    CloseSquareOutline,
    CloseSquareFill,
    CloudFill,
    CloseSquareTwoTone,
    CloudDownloadOutline,
    CloudTwoTone,
    CloudServerOutline,
    CloudUploadOutline,
    CloudSyncOutline,
    ClusterOutline,
    CodeSandboxCircleFill,
    CodeFill,
    CodepenCircleOutline,
    CloudOutline,
    CodeSandboxOutline,
    CodeOutline,
    CodeSandboxSquareFill,
    CodeTwoTone,
    CodepenSquareFill,
    CodepenOutline,
    CoffeeOutline,
    ColumnWidthOutline,
    CompressOutline,
    ColumnHeightOutline,
    CodepenCircleFill,
    CompassTwoTone,
    CommentOutline,
    ContainerFill,
    CompassOutline,
    ConsoleSqlOutline,
    ContactsOutline,
    ContainerTwoTone,
    ContactsFill,
    ContactsTwoTone,
    ContainerOutline,
    ControlFill,
    CopyFill,
    CopyOutline,
    CompassFill,
    CopyTwoTone,
    CopyrightOutline,
    CopyrightCircleOutline,
    ControlTwoTone,
    ControlOutline,
    CreditCardFill,
    CopyrightTwoTone,
    CrownFill,
    CopyrightCircleFill,
    CrownOutline,
    CustomerServiceTwoTone,
    CreditCardOutline,
    CustomerServiceOutline,
    DashboardTwoTone,
    CrownTwoTone,
    CreditCardTwoTone,
    CustomerServiceFill,
    DashboardFill,
    DashOutline,
    DatabaseOutline,
    DatabaseTwoTone,
    DatabaseFill,
    DashboardOutline,
    DeleteTwoTone,
    DeleteRowOutline,
    DeleteColumnOutline,
    DeliveredProcedureOutline,
    DeleteOutline,
    CopyrightCircleTwoTone,
    DesktopOutline,
    DeleteFill,
    DiffOutline,
    DiffFill,
    DeploymentUnitOutline,
    DiffTwoTone,
    DingtalkOutline,
    DollarCircleFill,
    DislikeFill,
    DingtalkSquareFill,
    DisconnectOutline,
    DollarCircleTwoTone,
    DollarOutline,
    DingtalkCircleFill,
    DislikeTwoTone,
    DollarTwoTone,
    DownCircleFill,
    DislikeOutline,
    DollarCircleOutline,
    DoubleLeftOutline,
    DownSquareFill,
    DownOutline,
    DownSquareOutline,
    DownSquareTwoTone,
    DownCircleTwoTone,
    DoubleRightOutline,
    DownCircleOutline,
    DownloadOutline,
    DotChartOutline,
    DribbbleCircleFill,
    DribbbleOutline,
    DribbbleSquareOutline,
    DropboxCircleFill,
    DingdingOutline,
    EditOutline,
    DribbbleSquareFill,
    DropboxSquareFill,
    EllipsisOutline,
    EnvironmentFill,
    EditFill,
    EnterOutline,
    EuroCircleFill,
    EuroTwoTone,
    EuroCircleOutline,
    EditTwoTone,
    EuroOutline,
    EnvironmentTwoTone,
    ExclamationCircleFill,
    ExpandAltOutline,
    EuroCircleTwoTone,
    ExclamationCircleTwoTone,
    EnvironmentOutline,
    ExperimentOutline,
    ExperimentFill,
    ExpandOutline,
    ExceptionOutline,
    ExportOutline,
    ExperimentTwoTone,
    ExclamationCircleOutline,
    ExclamationOutline,
    EyeFill,
    EyeInvisibleFill,
    EyeInvisibleTwoTone,
    DropboxOutline,
    DragOutline,
    FacebookOutline,
    FacebookFill,
    EyeTwoTone,
    EyeOutline,
    FastForwardFill,
    FieldBinaryOutline,
    FieldNumberOutline,
    FastBackwardOutline,
    FileAddFill,
    FastBackwardFill,
    FileExcelFill,
    FastForwardOutline,
    FieldStringOutline,
    FileDoneOutline,
    FileAddTwoTone,
    FileExcelTwoTone,
    FileExclamationFill,
    FileAddOutline,
    FileExclamationOutline,
    FieldTimeOutline,
    FileImageTwoTone,
    FileExcelOutline,
    FileExclamationTwoTone,
    FileImageFill,
    FileGifOutline,
    FileFill,
    FileMarkdownTwoTone,
    FileMarkdownOutline,
    FallOutline,
    FileImageOutline,
    EyeInvisibleOutline,
    FilePdfOutline,
    FileSearchOutline,
    FilePptTwoTone,
    FilePdfTwoTone,
    FileJpgOutline,
    FileTextFill,
    FilePptOutline,
    FileSyncOutline,
    FilePptFill,
    FileUnknownOutline,
    FileProtectOutline,
    FileTextTwoTone,
    FileWordFill,
    FileUnknownTwoTone,
    FileWordTwoTone,
    FileUnknownFill,
    FileTextOutline,
    FileZipFill,
    FilterTwoTone,
    FilterFill,
    FileWordOutline,
    FireOutline,
    FireTwoTone,
    FileZipOutline,
    FilterOutline,
    FlagTwoTone,
    FileTwoTone,
    FilePdfFill,
    FileOutline,
    FileMarkdownFill,
    FileZipTwoTone,
    FlagOutline,
    FolderAddTwoTone,
    FolderOpenFill,
    FireFill,
    FlagFill,
    FolderOutline,
    FolderViewOutline,
    FolderTwoTone,
    FontColorsOutline,
    FolderOpenTwoTone,
    FolderFill,
    ForwardOutline,
    FolderOpenOutline,
    ForkOutline,
    ForwardFill,
    FormatPainterOutline,
    FormatPainterFill,
    FormOutline,
    FrownFill,
    FrownTwoTone,
    FullscreenOutline,
    FontSizeOutline,
    FundFill,
    FunctionOutline,
    FundViewOutline,
    FullscreenExitOutline,
    GifOutline,
    FundProjectionScreenOutline,
    FundTwoTone,
    FolderAddFill,
    FunnelPlotTwoTone,
    GiftOutline,
    FunnelPlotFill,
    FundOutline,
    FrownOutline,
    GithubOutline,
    GoldFill,
    FolderAddOutline,
    GitlabFill,
    GiftFill,
    GitlabOutline,
    GoldTwoTone,
    GoogleCircleFill,
    GiftTwoTone,
    GooglePlusCircleFill,
    GoldOutline,
    GithubFill,
    GoogleOutline,
    GooglePlusOutline,
    GoogleSquareFill,
    GoldenFill,
    HddTwoTone,
    GooglePlusSquareFill,
    GlobalOutline,
    HeartOutline,
    HeartTwoTone,
    GroupOutline,
    HeartFill,
    HeatMapOutline,
    GatewayOutline,
    FunnelPlotOutline,
    HddFill,
    HomeFill,
    HighlightFill,
    HomeOutline,
    HistoryOutline,
    HighlightOutline,
    HddOutline,
    HourglassFill,
    HomeTwoTone,
    HourglassTwoTone,
    Html5Outline,
    Html5Fill,
    IdcardFill,
    Html5TwoTone,
    HourglassOutline,
    IdcardTwoTone,
    IdcardOutline,
    IeOutline,
    IeCircleFill,
    IeSquareFill,
    InboxOutline,
    ImportOutline,
    InfoCircleOutline,
    InfoCircleTwoTone,
    InsertRowAboveOutline,
    InsertRowRightOutline,
    InfoCircleFill,
    InfoOutline,
    InsertRowBelowOutline,
    HighlightTwoTone,
    InsuranceFill,
    InstagramFill,
    InteractionFill,
    InsertRowLeftOutline,
    InstagramOutline,
    InteractionOutline,
    ItalicOutline,
    InteractionTwoTone,
    LayoutOutline,
    IssuesCloseOutline,
    LayoutFill,
    LaptopOutline,
    LeftCircleFill,
    LayoutTwoTone,
    KeyOutline,
    LeftOutline,
    LeftCircleOutline,
    LeftSquareOutline,
    LeftSquareFill,
    LeftCircleTwoTone,
    LikeFill,
    LeftSquareTwoTone,
    LineOutline,
    LikeTwoTone,
    LinkedinOutline,
    LineChartOutline,
    LineHeightOutline,
    LinkedinFill,
    LinkOutline,
    LikeOutline,
    InsuranceOutline,
    Loading3QuartersOutline,
    LockFill,
    InsuranceTwoTone,
    MacCommandOutline,
    LockTwoTone,
    LoadingOutline,
    MailOutline,
    LoginOutline,
    MedicineBoxOutline,
    MailFill,
    MailTwoTone,
    MacCommandFill,
    ManOutline,
    MedicineBoxFill,
    MedicineBoxTwoTone,
    MediumCircleFill,
    MediumOutline,
    MehFill,
    MediumWorkmarkOutline,
    MenuFoldOutline,
    MehOutline,
    MediumSquareFill,
    MessageTwoTone,
    MehTwoTone,
    MergeCellsOutline,
    MinusCircleFill,
    MenuOutline,
    MenuUnfoldOutline,
    MessageFill,
    MinusCircleTwoTone,
    LockOutline,
    MinusOutline,
    MinusCircleOutline,
    LogoutOutline,
    MessageOutline,
    MoneyCollectFill,
    MinusSquareOutline,
    MinusSquareTwoTone,
    MobileOutline,
    MobileTwoTone,
    MoneyCollectOutline,
    MoreOutline,
    NotificationFill,
    NotificationOutline,
    MoneyCollectTwoTone,
    NodeIndexOutline,
    NodeExpandOutline,
    MonitorOutline,
    OrderedListOutline,
    NodeCollapseOutline,
    NumberOutline,
    PaperClipOutline,
    NotificationTwoTone,
    PauseCircleFill,
    PartitionOutline,
    PauseOutline,
    OneToOneOutline,
    PayCircleOutline,
    PayCircleFill,
    MinusSquareFill,
    PauseCircleOutline,
    PauseCircleTwoTone,
    PicCenterOutline,
    PicRightOutline,
    PercentageOutline,
    MobileFill,
    PictureOutline,
    PictureFill,
    PhoneTwoTone,
    PhoneFill,
    PieChartFill,
    PictureTwoTone,
    PieChartOutline,
    PlaySquareFill,
    PlayCircleTwoTone,
    PlayCircleFill,
    PlusCircleFill,
    PlaySquareTwoTone,
    PlaySquareOutline,
    PlayCircleOutline,
    PieChartTwoTone,
    PlusCircleOutline,
    PlusSquareFill,
    PoundCircleFill,
    PlusSquareOutline,
    PlusOutline,
    PoundOutline,
    PoundCircleOutline,
    PlusSquareTwoTone,
    PlusCircleTwoTone,
    PoweroffOutline,
    PoundCircleTwoTone,
    PhoneOutline,
    PrinterFill,
    PicLeftOutline,
    ProjectTwoTone,
    PrinterOutline,
    ProjectFill,
    ProfileOutline,
    ProfileTwoTone,
    ProjectOutline,
    PropertySafetyFill,
    PullRequestOutline,
    PropertySafetyOutline,
    PushpinOutline,
    PushpinTwoTone,
    PropertySafetyTwoTone,
    PushpinFill,
    QqOutline,
    QqCircleFill,
    QrcodeOutline,
    QqSquareFill,
    QuestionCircleTwoTone,
    QuestionCircleFill,
    RadarChartOutline,
    RadiusUprightOutline,
    QuestionCircleOutline,
    QuestionOutline,
    ReadFill,
    RadiusUpleftOutline,
    RadiusBottomleftOutline,
    RadiusSettingOutline,
    RadiusBottomrightOutline,
    ProfileFill,
    PrinterTwoTone,
    ReadOutline,
    ReconciliationFill,
    ReloadOutline,
    ReconciliationOutline,
    RedEnvelopeTwoTone,
    RedditCircleFill,
    RedoOutline,
    RedEnvelopeFill,
    RedditOutline,
    RestTwoTone,
    RightCircleOutline,
    RestOutline,
    RedditSquareFill,
    RestFill,
    RightCircleTwoTone,
    RightOutline,
    RightSquareFill,
    RightCircleFill,
    RightSquareOutline,
    RetweetOutline,
    RiseOutline,
    RightSquareTwoTone,
    RobotFill,
    RocketOutline,
    RobotOutline,
    RocketTwoTone,
    RocketFill,
    RedEnvelopeOutline,
    RollbackOutline,
    RotateRightOutline,
    RotateLeftOutline,
    ReconciliationTwoTone,
    SafetyCertificateTwoTone,
    SaveOutline,
    SafetyOutline,
    SaveFill,
    SaveTwoTone,
    ScheduleFill,
    SafetyCertificateOutline,
    ScanOutline,
    ScheduleTwoTone,
    SearchOutline,
    ScheduleOutline,
    SecurityScanTwoTone,
    SecurityScanOutline,
    ScissorOutline,
    SelectOutline,
    SecurityScanFill,
    SendOutline,
    SettingOutline,
    SettingTwoTone,
    SettingFill,
    ShareAltOutline,
    ShopOutline,
    ShopFill,
    ShopTwoTone,
    ShrinkOutline,
    ShakeOutline,
    ShoppingOutline,
    ShoppingCartOutline,
    ShoppingFill,
    SisternodeOutline,
    ShoppingTwoTone,
    SafetyCertificateFill,
    SkinOutline,
    SignalFill,
    SketchOutline,
    SkinTwoTone,
    SketchSquareFill,
    SkypeFill,
    SkinFill,
    SlackCircleFill,
    SlackSquareFill,
    SlidersTwoTone,
    SkypeOutline,
    SlidersFill,
    SlackSquareOutline,
    SmallDashOutline,
    SmileTwoTone,
    SlidersOutline,
    SnippetsFill,
    SnippetsOutline,
    SmileOutline,
    SolutionOutline,
    SlackOutline,
    SnippetsTwoTone,
    SoundTwoTone,
    SortAscendingOutline,
    SoundFill,
    SortDescendingOutline,
    SmileFill,
    SoundOutline,
    SplitCellsOutline,
    SketchCircleFill,
    StarOutline,
    StockOutline,
    StarTwoTone,
    StepForwardFill,
    StarFill,
    StepBackwardFill,
    StepForwardOutline,
    StopFill,
    SubnodeOutline,
    SwapLeftOutline,
    StopOutline,
    StopTwoTone,
    SwapRightOutline,
    SwapOutline,
    SwitcherTwoTone,
    SwitcherOutline,
    SyncOutline,
    StrikethroughOutline,
    SwitcherFill,
    TagOutline,
    TabletTwoTone,
    TabletOutline,
    TabletFill,
    TableOutline,
    TagsFill,
    TagFill,
    TagsTwoTone,
    TaobaoCircleOutline,
    StepBackwardOutline,
    TagsOutline,
    TagTwoTone,
    TaobaoOutline,
    ThunderboltOutline,
    TaobaoSquareFill,
    TeamOutline,
    TaobaoCircleFill,
    ThunderboltTwoTone,
    ToolFill,
    ThunderboltFill,
    ToTopOutline,
    ToolOutline,
    ToolTwoTone,
    TrademarkCircleFill,
    TrophyFill,
    TrademarkCircleTwoTone,
    TransactionOutline,
    TrademarkCircleOutline,
    TranslationOutline,
    TwitterCircleFill,
    TrophyOutline,
    TrademarkOutline,
    TrophyTwoTone,
    TwitterSquareFill,
    UnlockFill,
    TwitterOutline,
    UnderlineOutline,
    UndoOutline,
    UpCircleFill,
    UngroupOutline,
    UnlockTwoTone,
    UnlockOutline,
    UpOutline,
    UsbFill,
    UpCircleOutline,
    UnorderedListOutline,
    UpCircleTwoTone,
    UpSquareFill,
    UpSquareOutline,
    UserAddOutline,
    UsbTwoTone,
    UsergroupDeleteOutline,
    UpSquareTwoTone,
    UserOutline,
    UsbOutline,
    UserDeleteOutline,
    UserSwitchOutline,
    VerticalLeftOutline,
    VerticalAlignBottomOutline,
    VerifiedOutline,
    UsergroupAddOutline,
    UploadOutline,
    VerticalAlignMiddleOutline,
    VerticalAlignTopOutline,
    VerticalRightOutline,
    VideoCameraOutline,
    VideoCameraAddOutline,
    VideoCameraTwoTone,
    VideoCameraFill,
    WalletOutline,
    WalletFill,
    WarningFill,
    WarningOutline,
    WechatOutline,
    WalletTwoTone,
    WeiboCircleFill,
    WarningTwoTone,
    WeiboSquareFill,
    WeiboOutline,
    WeiboSquareOutline,
    WeiboCircleOutline,
    WechatFill,
    WhatsAppOutline,
    WifiOutline,
    WomanOutline,
    YoutubeFill,
    YahooOutline,
    WindowsFill,
    WindowsOutline,
    YoutubeOutline,
    YuqueOutline,
    ZhihuCircleFill,
    YuqueFill,
    ZhihuOutline,
    ZhihuSquareFill,
    ZoomInOutline,
    ZoomOutOutline,
    YahooFill
];

/**
 * Generated bundle index. Do not edit.
 */

export { ICONS, YZ_SHARED_YELON_MODULES, YZ_SHARED_ZORRO_MODULES, YzSharedModule };
//# sourceMappingURL=shared.js.map
