import { AfterViewInit, EventEmitter, OnInit } from '@angular/core';
import { STComponent, STData } from '@yelon/abc/st';
import { SFComponent, SFSchema, SFValue } from '@yelon/form';
import { YunzaiTableUser, YunzaiTableUserParam, YunzaiTableUserProps, YunzaiTableUserRole, YunzaiTableUserState } from './yunzai-table-user.types';
import { YunzaiTableUserService } from "./yunzai-table-user.service";
import * as i0 from "@angular/core";
export declare class YunzaiTableUserComponent implements OnInit, AfterViewInit {
    private service;
    st: STComponent;
    sf: SFComponent;
    props?: YunzaiTableUserProps;
    readonly onChecked: EventEmitter<YunzaiTableUser[]>;
    private $destroy;
    state: YunzaiTableUserState;
    get wrapped(): boolean;
    get schema(): SFSchema;
    get disableCheck(): boolean;
    get pageCheck(): boolean;
    get hasCheck(): boolean;
    get list(): boolean;
    get checked(): YunzaiTableUser[];
    get scroll(): {
        x?: string | null;
        y?: string | null;
    };
    get inSearch(): boolean;
    get userIds(): string[];
    constructor(service: YunzaiTableUserService);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    setupPropsToState(): void;
    setupTable(): void;
    setupPropsData(): void;
    setupPropsPage(): void;
    setupPropsColumns(): void;
    setupPropsFilteredColumns(): void;
    setupPropsCustomColumns(): void;
    setupPropsChecked(): void;
    setupTableData(): void;
    setupTablePage(): void;
    setupTableColumn(): void;
    setupTableRequest(): void;
    setupTableResponse(): void;
    resetChecked(): void;
    onCheckedItem(data: YunzaiTableUser): void;
    onCheckedAll(e: any): void;
    isChecked(data: STData): boolean;
    isAllChecked(): boolean;
    isArraySubset(subset: any[], superset: any[]): boolean;
    renderRoles(roles: YunzaiTableUserRole[]): string;
    unCheck(user: YunzaiTableUser): void;
    unCheckAll(): void;
    hookSearch(): void;
    onSearch(value?: SFValue): void;
    onReset(): void;
    onQuery(): void;
    setTableParam(param: YunzaiTableUserParam): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<YunzaiTableUserComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<YunzaiTableUserComponent, "yunzai-table-user", never, { "props": { "alias": "props"; "required": false; }; }, { "onChecked": "onChecked"; }, never, never, false, never>;
}
