import { Injector, OnDestroy, OnInit } from '@angular/core';
import { _HttpClient } from '@yelon/theme';
import { LayoutNavApplicationState, YunzaiConfigService, YunzaiNavTopic } from '@yelon/util';
import { NzSafeAny } from 'ng-zorro-antd/core/types';
import { YunzaiI18NService } from '../yunzai-i18n.service';
import * as i0 from "@angular/core";
export declare class LayoutNavApplicationComponent implements OnInit, OnDestroy {
    private i18n;
    private http;
    private inject;
    private configService;
    private win;
    private bis;
    private $destroy;
    state: LayoutNavApplicationState;
    get showAllMenu(): boolean;
    get showMineMenu(): boolean;
    constructor(i18n: YunzaiI18NService, http: _HttpClient, inject: Injector, configService: YunzaiConfigService, win: NzSafeAny);
    ngOnInit(): void;
    fetchAllTopic(): void;
    attachNav(type: 'all' | 'mine' | 'other', topic?: YunzaiNavTopic): void;
    clearSearch(): void;
    displayAllNav(): void;
    displayMineNav(): void;
    displayOtherNav(topic: YunzaiNavTopic): void;
    diffChange(flag?: boolean): void;
    open(topic: YunzaiNavTopic): void;
    onSearch(): void;
    ngOnDestroy(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<LayoutNavApplicationComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<LayoutNavApplicationComponent, "layout-nav-application", never, {}, {}, never, never, false, never>;
}
